src/ChercherTrouver/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('', views.page_accueil_view),
    path('accounts/', include('accounts.urls')),
    path('objects/', include('objects.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from .views import(
        accounts_signup_view,
        accounts_login_view,
        accounts_logout_view,
        ) 

app_name = 'accounts'

urlpatterns = [
        path('signup/', accounts_signup_view, name='accounts_signup'),
        path('login/', accounts_login_view, name='accounts_login'),
        path('logout/', accounts_logout_view, name='accounts_logout'),
]

src/objects/urls.py
from django.urls import path
from .views import object_list_view, object_detail_view

app_name = 'objects'

urlpatterns = [
        path('', object_list_view, name='objects_list'),
        path('<int:id>/', object_detail_view, name='objects_detail'),
        ]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    numero_de_tel = models.CharField(max_length=13)
    numero_de_chambre = models.CharField(max_length = 3)
    genre = models.CharField(max_length = 1, choices = [
        ('M', 'Masculin'),
        ('F', 'Feminin'),
        ('A', 'Autre'),
    ]) 

src/objects/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class objetPerdu(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True)
    name = models.CharField(max_length=15)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("objects:objects_detail", kwargs={"id":self.id})

src/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserCustomForm(forms.ModelForm):
    password = forms.CharField(max_length=15, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','password', 'email']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['numero_de_tel', 'numero_de_chambre', 'genre']

src/ChercherTrouver/views.py
from django.shortcuts import render
from django.http import HttpResponse

def page_accueil_view(request):
    return render(request, 'ChercherTrouver/page_accueil.html')

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import UserCustomForm, UserProfileForm 
from django.contrib.auth.decorators import login_required

# Create your views here.
def accounts_signup_view(request):
    if request.method == 'POST':
        user_form = UserCustomForm(request.POST or None)
        profile_form = UserProfileForm(request.POST or None)
        if user_form.is_valid() and profile_form.is_valid():
            user_form = user_form.save()
            profile_form.save(commit=False)
            profile_form.user = user_form
            profile_form.save()
            login(request, user_form)
            return redirect('objects:objects_list')     
    else:
        user_form = UserCustomForm()
        profile_form = UserProfileForm()
    return render(request, 'accounts/accounts_signup.html', {'user_form':user_form, 'profile_form':profile_form})


def accounts_login_view(request):
    if request.method == 'POST':
       form = AuthenticationForm(data=request.POST)
       if form.is_valid():
            user = form.get_user()
            login(request, user)
            redirect('objects:objects_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/accounts_login.html', {'form':form})

@login_required(login_url='accounts/login')
def accounts_logout_view(request):
   if request.method == 'POST':
       logout(request)
       return redirect('objects:objects_list')

src/objects/views.py
from django.shortcuts import render, get_object_or_404
from .models import objetPerdu
from django.http import HttpResponse

# Create your views here.
def object_list_view(request):
    objets = objetPerdu.objects.all().order_by('date')
    context = {'objets':objets}
    return render(request, 'objects/object_list.html', context)

def object_detail_view(request, id):
    obj = get_object_or_404(objetPerdu, id=id)
    context = {
            'object':obj,
    }
    return render(request, 'objects/objects_detail.html', context)

src/accounts/templates/accounts/accounts_login.html
{% extends 'base_layout.html' %}
{% block content %}
  <h1>Log In</h1>
  <form class="form-signin" action="{% url 'accounts:accounts_login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignIn">
  </form>
  <a class="btn_signup" href='{% url 'accounts:accounts_signup' %}'>
        <button>SignUp</button>
  </a>

{% endblock %}

src/accounts/templates/accounts/accounts_signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>SignUp</h1>
  <form class="form-signup" action="{% url 'accounts:accounts_signup' %}" method="post">
    {% csrf_token %}
    {% csrf_token %}
    {{ user_form }}
    {{ profile_form }}
    <input type="submit" value="SignUp">
  </form>
{% endblock %}

src/objects/templates/objects/object_list.html
{% extends 'base_layout.html' %}
{% block content %}
  <h1>Page Principale</h1>
  {% for instance in objets %}
  <p>
  {{ instance.id }} - <a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a>
  </p>
  {% endfor %}

{% endblock %}

src/objects/templates/objects/objects_detail.html
{% extends 'base_layout.html' %}
{% block content %}
  <h1>Details</h1>
  <img src={{ object.thumb.url }}> 
  <p>{{ object.name }}</p>
  <p>{{ object.description }}</p>
{% endblock %}

src/templates/ChercherTrouver/page_accueil.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>ChercherTrouver</title>
  </head>
  <body>
    <header>
      <p>ChercherTrouver</p>
    </header>
    <div class="wrapper">
      <h1>Page Accueil</h1>
      <p>ChercherTrouver est une application cree par Samuel Michael Vanie, Sanoko Alassane, </br>
        Ojo Victory, Kone Moussa et Diomande Sai pour gerer les differents objets perdus a l'INP-HB</br>
        de Yamoussoukro vu les difficultes que les etudiants ont a retrouver leurs biens. Cette plateforme</br>
        a ete mise en place pour concentrer l'information en un seul endroit.
      </p>
      <a class="btn_continuer" href='{% url 'accounts:accounts_login' %}'>
        <button>Continuer</button>
      </a>
    </div>
  </body>

src/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>ChercherTrouver</title>
  </head>
  <body>
    <header class="wrapper">
      <nav>
        <ul>
          <li>
            <p>ChercherTrouver</p>
            {% if user.is_authenticated %}
              <form class="logout-link" action = {% url 'accounts:accounts_logout' %} method="POST">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            {% else %}
              <li><a href="{% url 'accounts:accounts_login'%}">Login</a></li>
              <li><a href="{% url 'accounts:accounts_signup' %}">SignUp</a></li>
            {% endif %}
          </li>
        </ul>
      </nav>
    </header>
    <div class="wrapper">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>